In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/swiggy.csv")

In [23]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["ID"].duplicated().sum()

np.int64(0)

In [11]:
df["Time_taken(min)"].head(20)

0     (min) 24
1     (min) 33
2     (min) 26
3     (min) 21
4     (min) 30
5     (min) 26
6     (min) 40
7     (min) 32
8     (min) 34
9     (min) 46
10    (min) 23
11    (min) 21
12    (min) 20
13    (min) 41
14    (min) 20
15    (min) 33
16    (min) 40
17    (min) 41
18    (min) 15
19    (min) 36
Name: Time_taken(min), dtype: str

In [18]:



df["Weatherconditions"].value_counts()

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

In [19]:
df["Delivery_person_Age"].value_counts().head(20)

Delivery_person_Age
35    2262
36    2260
37    2227
30    2226
38    2219
24    2210
32    2202
22    2196
29    2191
33    2187
28    2179
25    2174
34    2166
26    2159
21    2153
27    2150
39    2144
20    2136
31    2120
23    2087
Name: count, dtype: int64

In [20]:
df["Delivery_person_Ratings"].value_counts().head(20)

Delivery_person_Ratings
4.8     7148
4.7     7142
4.9     7041
4.6     6940
5       3996
4.5     3303
NaN     1908
4.1     1430
4.2     1418
4.3     1409
4.4     1361
4       1077
3.5      249
3.8      228
3.7      225
3.6      207
3.9      197
6         53
1         38
3.4       32
Name: count, dtype: int64

In [24]:
df["multiple_deliveries"].value_counts()

multiple_deliveries
1       28159
0       14095
2        1985
NaN       993
3         361
Name: count, dtype: int64

In [26]:
df["Road_traffic_density"].value_counts(dropna=False)

Road_traffic_density
Low        15477
Jam        14143
Medium     10947
High        4425
NaN          601
Name: count, dtype: int64

In [28]:
df["Festival"].value_counts(dropna=False)

Festival
No      44469
Yes       896
NaN       228
Name: count, dtype: int64

In [30]:
df["City"].value_counts(dropna=False)

City
Metropolitian     34093
Urban             10136
NaN                1200
Semi-Urban          164
Name: count, dtype: int64

In [32]:
raw_df = pd.read_csv("../data/raw/swiggy.csv")

In [33]:
raw_df.shape

(45593, 20)

In [35]:
raw_df.dtypes

ID                                 str
Delivery_person_ID                 str
Delivery_person_Age                str
Delivery_person_Ratings            str
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                         str
Time_Orderd                        str
Time_Order_picked                  str
Weatherconditions                  str
Road_traffic_density               str
Vehicle_condition                int64
Type_of_order                      str
Type_of_vehicle                    str
multiple_deliveries                str
Festival                           str
City                               str
Time_taken(min)                    str
dtype: object

In [37]:

raw_df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [39]:
raw_df["Time_taken(min)"].head(10)

0    (min) 24
1    (min) 33
2    (min) 26
3    (min) 21
4    (min) 30
5    (min) 26
6    (min) 40
7    (min) 32
8    (min) 34
9    (min) 46
Name: Time_taken(min), dtype: str

In [46]:
clean_df = pd.read_csv(
    "../data/processed/swiggy_cleaned.csv"
)

In [43]:
clean_df.shape

(45593, 20)

In [44]:
clean_df.dtypes

ID                                 str
Delivery_person_ID                 str
Delivery_person_Age              int64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                         str
Time_Orderd                        str
Time_Order_picked                  str
Weatherconditions                  str
Road_traffic_density               str
Vehicle_condition                int64
Type_of_order                      str
Type_of_vehicle                    str
multiple_deliveries              int64
Festival                           str
City                               str
Time_taken(min)                  int64
dtype: object

In [48]:
clean_df["pickup_delay_minutes"].describe()

KeyError: 'pickup_delay_minutes'

In [50]:
from src.feature_engineering import (
    haversine_distance,
    create_time_features,
    create_pickup_delay_feature
)

ModuleNotFoundError: No module named 'src'

In [52]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [54]:
from src.feature_engineering import (
    haversine_distance,
    create_time_features,
    create_pickup_delay_feature
)

In [56]:
import pandas as pd

clean_df = pd.read_csv(
    "../data/processed/swiggy_cleaned.csv"
)

In [58]:
clean_df["Distance_km"] = haversine_distance(
    clean_df["Restaurant_latitude"],
    clean_df["Restaurant_longitude"],
    clean_df["Delivery_location_latitude"],
    clean_df["Delivery_location_longitude"]
)

In [60]:
clean_df = create_time_features(clean_df)

In [62]:
clean_df = create_pickup_delay_feature(clean_df)

In [64]:
clean_df[
    [
        "Time_Orderd",
        "Time_Order_picked",
        "order_hour",
        "pickup_delay_minutes",
        "Distance_km"
    ]
].head(10)

  Time_Orderd Time_Order_picked  order_hour  pickup_delay_minutes  Distance_km
0    11:30:00          11:45:00        11.0                  15.0     3.025149
1    19:45:00          19:50:00        19.0                   5.0    20.183530
2    08:30:00          08:45:00         8.0                  15.0     1.552758
3    18:00:00          18:10:00        18.0                  10.0     7.790401
4    13:30:00          13:45:00        13.0                  15.0     6.210138
5    21:20:00          21:30:00        21.0                  10.0     4.610365
6    19:15:00          19:30:00        19.0                  15.0    16.600361
7    17:25:00          17:30:00        17.0                   5.0    20.205253
8    20:55:00          21:05:00        20.0                  10.0    19.975520
9    21:55:00          22:10:00        21.0                  15.0    10.280582

In [78]:
clean_df["pickup_delay_minutes"].describe()

count    43862.000000
mean         9.989399
std          4.087516
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: pickup_delay_minutes, dtype: float64

In [79]:
(clean_df["pickup_delay_minutes"] < 0).sum()

np.int64(0)

In [80]:
clean_df["pickup_delay_minutes"].max()

np.float64(15.0)

In [81]:
clean_df["pickup_delay_minutes"].isnull().sum()

np.int64(1731)

In [100]:
from importlib import reload
import src.feature_engineering as fe

reload(fe)

In [99]:
clean_df = pd.read_csv(
    "../data/processed/swiggy_cleaned.csv"
)

In [86]:
clean_df["Distance_km"] = fe.haversine_distance(
    clean_df["Restaurant_latitude"],
    clean_df["Restaurant_longitude"],
    clean_df["Delivery_location_latitude"],
    clean_df["Delivery_location_longitude"]
)

clean_df = fe.create_time_features(clean_df)

clean_df = fe.create_pickup_delay_feature(clean_df)
clean_df = fe.create_peak_hour_feature(
    clean_df
)

In [88]:
clean_df[
    [
        "Time_Orderd",
        "order_hour",
        "is_peak_hour"
    ]
].head(20)

   Time_Orderd  order_hour  is_peak_hour
0     11:30:00        11.0             0
1     19:45:00        19.0             1
2     08:30:00         8.0             0
3     18:00:00        18.0             0
4     13:30:00        13.0             1
5     21:20:00        21.0             1
6     19:15:00        19.0             1
7     17:25:00        17.0             0
8     20:55:00        20.0             1
9     21:55:00        21.0             1
10    14:55:00        14.0             1
11    17:30:00        17.0             0
12    09:20:00         9.0             0
13    19:50:00        19.0             1
14    20:25:00        20.0             1
15    14:55:00        14.0             1
16    20:30:00        20.0             1
17    20:40:00        20.0             1
18    21:15:00        21.0             1
19    20:20:00        20.0             1

In [90]:
clean_df["is_peak_hour"].value_counts()

is_peak_hour
0    24730
1    20863
Name: count, dtype: int64

In [92]:
clean_df.columns.tolist()

['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weatherconditions',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken(min)',
 'Distance_km',
 'order_hour',
 'day_of_week',
 'month',
 'is_weekend',
 'pickup_delay_minutes',
 'is_peak_hour']

In [94]:
clean_df[
    [
        "Distance_km",
        "order_hour",
        "day_of_week",
        "month",
        "is_weekend",
        "is_peak_hour",
        "pickup_delay_minutes",
        "Time_taken(min)"
    ]
].describe()

,Distance_km,order_hour,day_of_week,month,is_weekend,is_peak_hour,pickup_delay_minutes,Time_taken(min)
count,45593.000000,43862.000000,45593.000000,45593.000000,45593.000000,45593.000000,43862.000000,45593.000000
mean,99.303911,17.423966,2.997675,2.980699,0.275020,0.457592,9.989399,26.294607
std,1099.731281,4.817856,1.969720,0.545906,0.446529,0.498204,4.087516,9.383806
min,1.465067,0.000000,0.000000,2.000000,0.000000,0.000000,5.000000,10.000000
25%,4.663493,15.000000,1.000000,3.000000,0.000000,0.000000,5.000000,19.000000
50%,9.264281,19.000000,3.000000,3.000000,0.000000,0.000000,10.000000,26.000000
75%,13.763977,21.000000,5.000000,3.000000,1.000000,1.000000,15.000000,32.000000
max,19692.674606,23.000000,6.000000,4.000000,1.000000,1.000000,15.000000,54.000000

In [96]:
clean_df[
    clean_df["Distance_km"] > 100
][
    [
        "Restaurant_latitude",
        "Restaurant_longitude",
        "Delivery_location_latitude",
        "Delivery_location_longitude",
        "Distance_km"
    ]
].head(20)

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Distance_km
92,-27.163303,78.057044,27.233303,78.127044,6048.631240
283,-27.165108,78.015053,27.225108,78.075053,6047.919478
289,-18.551440,-73.804855,18.611440,73.864855,16612.239055
425,-30.366322,-78.070453,30.496322,78.200453,17744.205087
534,-12.325461,-76.632278,12.385461,76.692278,17118.828366
583,-12.316967,76.603067,12.326967,76.613067,2740.280655
762,-23.359194,-85.325447,23.449194,85.415447,19070.337839
1059,-26.477750,-80.351569,26.487750,80.361569,18097.339322
1091,-15.546594,73.760431,15.606594,73.820431,3464.082720
1157,-12.337978,76.616792,12.387978,76.666792,2749.406397
1286,-27.160934,-78.044095,27.180934,78.064095,17655.222561
1378,-26.905190,-75.810753,26.975190,75.880753,17214.881134
1451,-17.459710,78.368855,17.549710,78.458855,3892.882349
1544,-26.914142,75.805704,27.024142,75.915704,5997.675070
1599,-19.176269,-72.836721,19.256269,72.916721,16425.191861
1783,-23.230791,77.437020,23.250791,77.457020,5168.516553
1976,-22.539129,88.365507,22.549129,88.375507,5013.585658
2101,-15.157944,73.950889,15.197944,73.990889,3375.423601
2138,-9.959778,76.296106,9.969778,76.306106,2216.065794
2200,-15.513150,73.783460,15.563150,73.833460,3455.531261

In [101]:
(clean_df["Distance_km"] > 100).sum()

KeyError: 'Distance_km'

In [103]:
clean_df = fe.clean_coordinates(clean_df)

In [104]:
clean_df["Distance_km"] = fe.haversine_distance(
    clean_df["Restaurant_latitude"],
    clean_df["Restaurant_longitude"],
    clean_df["Delivery_location_latitude"],
    clean_df["Delivery_location_longitude"]
)

In [106]:
clean_df["Distance_km"].describe()

count    45593.000000
mean         9.735394
std          5.608507
min          1.465067
25%          4.663345
50%          9.220148
75%         13.681492
max         20.969489
Name: Distance_km, dtype: float64

In [108]:
(clean_df["Distance_km"] > 100).sum()

np.int64(0)

In [110]:
feature_columns = [
    "Distance_km",
    "order_hour",
    "day_of_week",
    "month",
    "is_weekend",
    "is_peak_hour",
    "pickup_delay_minutes",
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "Weatherconditions",
    "Road_traffic_density",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City"
]

In [112]:
target_column = "Time_taken(min)"

In [114]:
model_df = clean_df[
    feature_columns + [target_column]
].copy()

KeyError: "['order_hour', 'day_of_week', 'month', 'is_weekend', 'is_peak_hour', 'pickup_delay_minutes'] not in index"

In [116]:
print("Columns in clean_df:")
print(clean_df.columns.tolist())

Columns in clean_df:
['ID', 'Delivery_person_ID', 'Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude', 'Restaurant_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude', 'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density', 'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)', 'Distance_km']

In [118]:
print("Features we requested:")
print(feature_columns)

Features we requested:
['Distance_km', 'order_hour', 'day_of_week', 'month', 'is_weekend', 'is_peak_hour', 'pickup_delay_minutes', 'Delivery_person_Age', 'Delivery_person_Ratings', 'Vehicle_condition', 'multiple_deliveries', 'Weatherconditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City']

In [120]:
missing_columns = [
    col
    for col in feature_columns + [target_column]
    if col not in clean_df.columns
]

print("Missing columns:")
print(missing_columns)

Missing columns:
['order_hour', 'day_of_week', 'month', 'is_weekend', 'is_peak_hour', 'pickup_delay_minutes']

In [122]:
from importlib import reload
import src.feature_engineering as fe

reload(fe)

In [124]:
clean_df = pd.read_csv(
    "../data/processed/swiggy_cleaned.csv"
)

In [127]:
clean_df = fe.clean_coordinates(clean_df)

In [128]:
clean_df["Distance_km"] = fe.haversine_distance(
    clean_df["Restaurant_latitude"],
    clean_df["Restaurant_longitude"],
    clean_df["Delivery_location_latitude"],
    clean_df["Delivery_location_longitude"]
)

In [130]:
clean_df = fe.create_time_features(clean_df)

In [132]:
clean_df[
    [
        "Order_Date",
        "Time_Orderd",
        "order_hour",
        "day_of_week",
        "month",
        "is_weekend"
    ]
].head()

  Order_Date Time_Orderd  order_hour  day_of_week  month  is_weekend
0 2022-03-19    11:30:00        11.0            5      3           1
1 2022-03-25    19:45:00        19.0            4      3           0
2 2022-03-19    08:30:00         8.0            5      3           1
3 2022-04-05    18:00:00        18.0            1      4           0
4 2022-03-26    13:30:00        13.0            5      3           1

In [136]:
clean_df = fe.create_pickup_delay_feature(clean_df)

In [138]:
clean_df[
    [
        "order_hour",
        "is_peak_hour"
    ]
].head(20)

KeyError: "['is_peak_hour'] not in index"

In [140]:
import pandas as pd
import numpy as np

# ==========================================
# 1. Load cleaned dataset
# ==========================================

clean_df = pd.read_csv(
    "../data/processed/swiggy_cleaned.csv"
)

print("Initial shape:", clean_df.shape)


# ==========================================
# 2. Clean geographic coordinates
# ==========================================

coordinate_columns = [
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude"
]

for column in coordinate_columns:
    clean_df[column] = clean_df[column].abs()


# ==========================================
# 3. Calculate Haversine distance
# ==========================================

def haversine_distance(lat1, lon1, lat2, lon2):

    R = 6371

    lat1 = np.radians(lat1)
    lat2 = np.radians(lat2)

    dlat = lat2 - lat1
    dlon = np.radians(lon2) - np.radians(lon1)

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arctan2(
        np.sqrt(a),
        np.sqrt(1 - a)
    )

    return R * c


clean_df["Distance_km"] = haversine_distance(
    clean_df["Restaurant_latitude"],
    clean_df["Restaurant_longitude"],
    clean_df["Delivery_location_latitude"],
    clean_df["Delivery_location_longitude"]
)


# ==========================================
# 4. Convert Order_Date to datetime
# ==========================================

clean_df["Order_Date"] = pd.to_datetime(
    clean_df["Order_Date"],
    errors="coerce"
)


# ==========================================
# 5. Create time features
# ==========================================

order_time = pd.to_datetime(
    clean_df["Time_Orderd"],
    format="%H:%M:%S",
    errors="coerce"
)

clean_df["order_hour"] = order_time.dt.hour

clean_df["day_of_week"] = (
    clean_df["Order_Date"].dt.dayofweek
)

clean_df["month"] = (
    clean_df["Order_Date"].dt.month
)

clean_df["is_weekend"] = (
    clean_df["day_of_week"] >= 5
).astype(int)


# ==========================================
# 6. Create pickup delay
# ==========================================

pickup_time = pd.to_datetime(
    clean_df["Time_Order_picked"],
    format="%H:%M:%S",
    errors="coerce"
)

order_minutes = (
    order_time.dt.hour * 60
    + order_time.dt.minute
)

pickup_minutes = (
    pickup_time.dt.hour * 60
    + pickup_time.dt.minute
)

pickup_delay = (
    pickup_minutes - order_minutes
)

# Handle midnight crossover
pickup_delay = pickup_delay.where(
    pickup_delay >= 0,
    pickup_delay + 1440
)

clean_df["pickup_delay_minutes"] = pickup_delay


# ==========================================
# 7. Create peak-hour feature
# ==========================================

clean_df["is_peak_hour"] = (
    clean_df["order_hour"].between(12, 14)
    |
    clean_df["order_hour"].between(19, 22)
).astype(int)


# ==========================================
# 8. Show resulting columns
# ==========================================

print("\nFeature engineering completed!")

print("\nNew features:")
print([
    "Distance_km",
    "order_hour",
    "day_of_week",
    "month",
    "is_weekend",
    "pickup_delay_minutes",
    "is_peak_hour"
])

print("\nFinal shape:", clean_df.shape)

Initial shape: (45593, 20)

Feature engineering completed!

New features:
['Distance_km', 'order_hour', 'day_of_week', 'month', 'is_weekend', 'pickup_delay_minutes', 'is_peak_hour']

Final shape: (45593, 27)

In [142]:
clean_df[
    [
        "Distance_km",
        "order_hour",
        "day_of_week",
        "month",
        "is_weekend",
        "pickup_delay_minutes",
        "is_peak_hour"
    ]
].head(10)

,Distance_km,order_hour,day_of_week,month,is_weekend,pickup_delay_minutes,is_peak_hour
0,3.025149,11.0,5,3,1,15.0,0
1,20.183530,19.0,4,3,0,5.0,1
2,1.552758,8.0,5,3,1,15.0,0
3,7.790401,18.0,1,4,0,10.0,0
4,6.210138,13.0,5,3,1,15.0,1
5,4.610365,21.0,4,3,0,10.0,1
6,16.600361,19.0,4,3,0,15.0,1
7,20.205253,17.0,0,3,0,5.0,0
8,19.975520,20.0,6,3,1,10.0,1
9,10.280582,21.0,5,2,1,15.0,1

In [144]:
required_features = [
    "Distance_km",
    "order_hour",
    "day_of_week",
    "month",
    "is_weekend",
    "is_peak_hour",
    "pickup_delay_minutes",
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "Weatherconditions",
    "Road_traffic_density",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City",
    "Time_taken(min)"
]

missing_columns = [
    col
    for col in required_features
    if col not in clean_df.columns
]

print("Missing columns:")

print(missing_columns)

Missing columns:
[]

In [146]:
feature_columns = [
    "Distance_km",
    "order_hour",
    "day_of_week",
    "month",
    "is_weekend",
    "is_peak_hour",
    "pickup_delay_minutes",
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "Weatherconditions",
    "Road_traffic_density",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City"
]

target_column = "Time_taken(min)"

model_df = clean_df[
    feature_columns + [target_column]
].copy()

In [148]:
print(model_df.shape)

(45593, 18)

In [150]:
model_df.isnull().sum()

Distance_km                   0
order_hour                 1731
day_of_week                   0
month                         0
is_weekend                    0
is_peak_hour                  0
pickup_delay_minutes       1731
Delivery_person_Age           0
Delivery_person_Ratings       0
Vehicle_condition             0
multiple_deliveries           0
Weatherconditions           616
Road_traffic_density          0
Type_of_order                 0
Type_of_vehicle               0
Festival                      0
City                          0
Time_taken(min)               0
dtype: int64

In [152]:
from pathlib import Path

Path("../data/features").mkdir(
    parents=True,
    exist_ok=True
)

model_df.to_csv(
    "../data/features/swiggy_features.csv",
    index=False
)

print("Feature dataset saved successfully!")
print("Shape:", model_df.shape)

Feature dataset saved successfully!
Shape: (45593, 18)

In [153]:
model_df.to_csv(
    "../data/features/swiggy_features.csv",
    index=False
)